name: Python package

on:
  push:
  pull_request:
  schedule:
    # run every Monday at 1:15 AM UTC - to test against the external reasons
    - cron: "15 1 * * 1"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11, windows-2019]
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install -U tox wheel pip setuptools
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
